SECRET_KEY = ''
DEBUG = True
LOGGING_PATH = 'logs/app.log'

DB_NAME = ''

SENDGRID_FROM_ADDRESS = ''
SENDGRID_INTERNAL_FROM_ADDRESS = ''
SENDGRID_INTERNAL_TO_ADDRESS = ''
SENDGRID_API_KEY = ''
MAIL_TEST_ENV = True
